### ISSUE TITLE
What's your project?

### ISSUE THREAD

**Issue by darioalessandro** [Hamdysaad20/proto2023-iti-#1]
Yo @Hamdysaad20 !! 

What are you building?

**Comment by Hamdysaad20** [comment]
I have been working with tailwind and react for so long 😂, I almost forgot the Css and Sass so just a small reminder project

**Comment by Hamdysaad20** [comment]
I'm working on other project tho ,divzoon community  ... and  now learning Rust to implement it there 😅 , but still not good enough to do it.  
So I left the project till I learn it

**Comment by darioalessandro** [comment]
ok 😄 what do you mean "not good enough" where did you get stuck?

**Comment by Hamdysaad20** [comment]
I got lost in Rust because I didn't see big project with it , so I don't have the full view,  and when I think about rust or Wasm I always think about the security issues, I don't know if it's me or that's a problem with rust community in YouTube (there isn't much resources)

**Comment by darioalessandro** [comment]
Hey @Hamdysaad20 what are the security issues with rust or Wasm? 

Also, many companies are adopting Rust, the company I work for @maymobility built all their video/telemetry streaming platform in rust, both vehicle and backend 😄 and there are big players like aws, meta building stuff in Rust.

As a youtuber, how can I help?

**Comment by Hamdysaad20** [comment]
First of all  thank you for asking and helping me , I just need full projects like for example  we can do routing in node .. how can we do it in rust .... we can feach data in node and pass it to react how can we do that with rust and pass it to react , is it even possible to do react in the Frontend and rust in the backend and if it's ok then how and how the file structure looks like  .

- last video you did I watch it like 4 times and still  don't get it,  but idk maybe because I don't have experience in the backend much  but  you can make like small segment in how we was doing it in node (so any one that worked with it can adopt and convert to rust easily. ).

-

**Comment by Hamdysaad20** [comment]
And for the security issues I saw this one 
https://www.forcepoint.com/blog/x-labs/webassembly-potentials-and-pitfalls#:~:text=There%20are%20several%20potential%20security,code%20in%20a%20victim's%20browser.

**Comment by darioalessandro** [comment]
Ok, thank you so much for your feedback, I need to put more work into breaking down these topics, @Funny News requested using svelte for the frontend and rust for backend, so I'll look into that.

Regarding creating an API with Rust and a frontend with React, yes, this is 100% possible. 

Regarding how to expose a REST endpoint like node/express: This is how to do it with Actix web: 

https://github.com/security-union/yew-actix-template/blob/522545763372d4bad93fdad2e941da0cd48f054c/actix-api/src/main.rs#L43-L44

So this is an HTTP GET with path `/login`.

Then you need to add the handle to the actix web instance https://github.com/security-union/yew-actix-template/blob/522545763372d4bad93fdad2e941da0cd48f054c/actix-api/src/main.rs#L175

**Comment by Hamdysaad20** [comment]
No thank you man for helping us . tbh I see alot of rust content on youtube and twitch but your videos is just something else,  fast and to the point .
Wish you luck with your career and I'd love to work with you on projects in the future 💙🤝🏻

**Comment by darioalessandro** [comment]
Regarding the security issues, I think that the article speculates about 2 topics:

## Potential security issues in wasm
Because wasm is a compiled binary, the tooling to detect malicious binary code needs to be built, this is true and applies to all native apps.

I am not too worried about it, as a developer I only use trusted 3rd parties, so it is ok that people can not see the source code in the browser, it is a nightmare for security engineers.

## Malicious apps
This is just like any other website, if the developer is mean, there's nothing to do about it XD.

**Comment by darioalessandro** [comment]
Thanks @Hamdysaad20 yeah, there are many projects in progress and I am looking forward to your contributions, I would be glad to collaborate and give a shoutout to your projects.

You can reach out to https://github.com/JasterV who worked with me in a couple of projects.

Lets stay in touch.
